name: Deploy theme

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync my theme
        env:
          source: './storefront/'
          #destination: 'bcivel@34.79.152.162:/var/www/html/wp-content/themes/storefront/'     
          destination: 'bcivel@35.195.196.219:/var/www/html/wp-content/themes/storefront/' 
        run: |
          echo "${{secrets.DEPLOY_KEY_UAT}}" > deploy_key
          chmod 600 ./deploy_key
          sudo rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /sass \
            ${{env.source}} ${{env.destination}}
